# Generated by Django 3.2.6 on 2021-11-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_remove_profile_head_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
