# Generated by Django 3.2.6 on 2021-10-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211003_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SP', 'Sport Wear'), ('M', 'Men'), ('W', 'Women')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
