# Generated by Django 3.2.6 on 2021-11-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_shippingaddress_number_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery_option',
            field=models.CharField(choices=[('S', 'Standard'), ('P', 'Premium')], default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SPORT', 'Sport Wear'), ('MEN', 'Men'), ('WOMEN', 'Women')], max_length=8),
        ),
    ]
